device: cuda
input_size_v1: 39
input_size_v2: 16
hidden_size: 256
num_layers: 2
bidirectional: False
proj_k: 20
calc_k: 20
avg_logit: True
blank: 40
num_classes: 41
epochs: 200
lr: 0.001
lr_decay: 100
batch_size: 32
resume: False
alpha: 10
seq_len: 1000


